trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore  $(solution)
    dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Restore and Build'

- script: |
    dotnet test --configuration $(buildConfiguration) --no-build --colllect "XPlat Code Coverage"
  displayName: 'Test'

- task: Docker@2
  inputs:
    containerRegistry: 'acrteste'
    repository: 'api-dio-test'
    command: 'buildAndPush'
    Dockerfile: './Dockerfile'